Add assessmentmodel-sdk module
Sage-Bionetworks/BridgeClientKMM pull request #15
Opened 2021-04-09 16:47 UTC by liujoshua

2021-04-15 19:29 UTC, syoung-smallwisdom requested changes
I'm pretty sure that this is adding the AssessmentModel to the common crossplatform code. Unfortunately, we can't do that or it will break iOS module structure. This needs to be added as a wrapper in the android code instead.

2021-04-19 22:52 UTC, nategbrown9 commented
> I'm pretty sure that this is adding the AssessmentModel to the common crossplatform code. Unfortunately, we can't do that or it will break iOS module structure. This needs to be added as a wrapper in the android code instead.

This is adding a new assessmentmodel-sdk module that depends on bridge-client and AssessmentModel.

2021-04-19 23:09 UTC, syoung-smallwisdom approved these changes

2021-04-27 20:25 UTC, nategbrown9 approved these changes
Looks good. Could remove the wizard generated Platform.kt and Greeting.kt files.

2021-04-29 21:49 UTC, merged