Handle http 410
Sage-Bionetworks/BridgeClientKMM pull request #197
Opened 2023-03-03 16:28 UTC by nategbrown9

Add a StateFlow that apps can observe to be notified of 410 app unsupported errors from Bridge. This will allow us to implement DHP-271 and DHP-272.

2023-03-03 18:03 UTC, syoung-smallwisdom requested changes
I'd like to see a few unit tests on this. 

1. Failed auth call
2. Failed app config call (doesn't require session_id)
3. Failed call that should be authenticated

Also, the case where the user is not authenticated should still tell the app that something is very wrong and the app needs to be updated. Kind of an edge case but is it really a "don't care"?

2023-03-03 18:03 UTC, syoung-smallwisdom commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/di/HttpClientModule.kt
> +    }
What happens when the auth calls return a 410? Then it can't get to the other calls that expect a signed in participant.

2023-03-03 18:03 UTC, syoung-smallwisdom commented on bridge-client/src/commonTest/kotlin/org/sagebionetworks/bridge/kmm/shared/TestUtils.kt
> +    override fun notifyUIOfBridgeError(statusCode: HttpStatusCode) {
This should save that it was called so that the status code can be inspected in the unit tests.

2023-03-03 18:03 UTC, syoung-smallwisdom commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/repo/AuthenticationRepository.kt
> +        // TODO: emm 2021-08-17 pass 412 (not consented) Bridge errors along to the UI to deal with.
Remove TODO comment.

2023-03-03 18:15 UTC, nategbrown9 commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/di/HttpClientModule.kt
> +    }
Good catch, this should be added to both Http clients.

2023-03-03 18:16 UTC, nategbrown9 commented on bridge-client/src/commonTest/kotlin/org/sagebionetworks/bridge/kmm/shared/TestUtils.kt
> +    override fun notifyUIOfBridgeError(statusCode: HttpStatusCode) {
I marked the PR as draft since I didn't yet have unit tests. Will fill this in as part of adding tests.

2023-03-03 18:16 UTC, nategbrown9 commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/repo/AuthenticationRepository.kt
> +        // TODO: emm 2021-08-17 pass 412 (not consented) Bridge errors along to the UI to deal with.
We aren't handling 412s yet, so I think the TODO still applies.

2023-03-07 18:58 UTC, nategbrown9 commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/di/HttpClientModule.kt
> +    }
Forgot that adding the AuthenticationRepository to the httpClient used for authentication creates a dependency loop (yeah we have tests that caught this). Other unauthenticated calls such as app config and study info use the other httpClient, so they will get the 410 handling.

2023-03-07 19:46 UTC, nategbrown9 commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/di/HttpClientModule.kt
> +    }
Added 410 handling to AuthenticationRepository for sign-in.

2023-03-07 19:46 UTC, nategbrown9 commented on bridge-client/src/commonTest/kotlin/org/sagebionetworks/bridge/kmm/shared/TestUtils.kt
> +    override fun notifyUIOfBridgeError(statusCode: HttpStatusCode) {
Now have tests

2023-03-07 21:43 UTC, syoung-smallwisdom approved these changes
Few questions. Otherwise, looks good.

2023-03-07 21:43 UTC, syoung-smallwisdom commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/repo/AuthenticationRepository.kt
> +    suspend fun requestPhoneSignIn(number: String, regionCode: String) : ResourceResult<Boolean> {
Is anyone using phone sign in?

2023-03-07 21:43 UTC, syoung-smallwisdom commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/repo/AuthenticationRepository.kt
> +    private fun getHttpStatusCode(error: Throwable) : HttpStatusCode? {
Several of the paths are not calling this. (both reauth calls, for example). Should they be? Or are you relying upon the fact that the reauth only gets called after a call has already failed?

2023-03-08 04:37 UTC, nategbrown9 commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/repo/AuthenticationRepository.kt
> +    suspend fun requestPhoneSignIn(number: String, regionCode: String) : ResourceResult<Boolean> {
Nope

2023-03-08 04:38 UTC, nategbrown9 commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/repo/AuthenticationRepository.kt
> +    private fun getHttpStatusCode(error: Throwable) : HttpStatusCode? {
I am assuming that reauth should only be called after a call has already failed, so the first call should trigger the 410.

2023-03-08 16:13 UTC, merged