Add validation of metadata.json file against schema as part of test
Sage-Bionetworks/BridgeClientKMM pull request #215
Opened 2023-05-24 23:19 UTC by nategbrown9

2023-05-25 19:08 UTC, Erin-Mounts approved these changes
looks good to me.

2023-05-25 19:08 UTC, Erin-Mounts commented on .github/workflows/check.yml
> +      # TODO: Figure out less fragile way of getting and setting path to jep -nbrown 5/25/13
Have you tried asking ChatGPT for help with this? ¯\\\_(ツ)\_/¯ just a thought

2023-05-25 20:11 UTC, syoung-smallwisdom requested changes

2023-05-25 20:11 UTC, syoung-smallwisdom commented on assessmentmodel-sdk/src/test/java/org/sagebionetworks/bridge/assessmentmodel/upload/AssessmentArchiverTest.kt
> +                    assertTrue(schemaErrors.isEmpty())
This is an old schema. Should be using https://github.com/Sage-Bionetworks/mobile-client-json/blob/main/schemas/v2/ArchiveMetadata.json

2023-05-25 20:11 UTC, syoung-smallwisdom commented on assessmentmodel-sdk/src/main/java/org/sagebionetworks/bridge/assessmentmodel/upload/AssessmentArchiver.kt
> +            taskIdentifier = assessmentResult.identifier,
This is an old schema. Latest is https://github.com/Sage-Bionetworks/mobile-client-json/blob/main/schemas/v2/ArchiveMetadata.json

2023-05-26 15:35 UTC, nategbrown9 commented
Found a java schema validator library that does what we need. Being able to run the same validator as BridgeDownstream didn't seem like it was worth the hassle of setting up Python. The other problem I found when trying to use it for the Android Mobile Toolbox App integration tests is that the python solution wont work for tests that run on a device or emulator.

2023-05-26 16:49 UTC, syoung-smallwisdom approved these changes
looks good

2023-05-30 16:52 UTC, merged