Fix DHP-1140: Add rest of adherence fields to upload metadata
Sage-Bionetworks/BridgeClientKMM pull request #238
Opened 2023-10-30 22:53 UTC by nategbrown9

2023-10-30 23:01 UTC, Erin-Mounts approved these changes
looks good to me

2023-10-30 23:05 UTC, syoung-smallwisdom requested changes
This will break iOS uploads.

Obj-c does not support Kotlin `JsonElement` objects. It also doesn't support automatic assignment to null so changes the `UploadMetadata` object must include building the XCFramework binary and fixing uploading to support it. Sorry.

2023-11-03 01:38 UTC, syoung-smallwisdom approved these changes
Need to update the XCFramework binary before merging. There is a build configuration that you can use: `createSwiftPackage`

I think that we are creating tech debt here. Really, we should have an upload request take an optional `AdherenceRecord` object rather than "metadata" where the "metadata" is expected to match a subset of the `AdherenceRecord` properties. Just too many calls to services and too much room for typos. That said, I recognize that doing so is a more time-consuming refactor. ¯\_(ツ)_/¯

2023-11-03 01:38 UTC, syoung-smallwisdom commented on bridge-client/src/commonMain/kotlin/org/sagebionetworks/bridge/kmm/shared/models/UploadMetadata.kt
> +    val clientData: JsonElement? = null
timezone?

2023-11-06 21:00 UTC, merged