Add study repository
Sage-Bionetworks/BridgeClientKMM pull request #46
Opened 2021-07-16 19:16 UTC by nategbrown9

Still need to test, but here it is.

2021-07-19 18:20 UTC, syoung-smallwisdom approved these changes

2021-07-19 20:06 UTC, syoung-smallwisdom requested changes
Upon further consideration, the flow doesn't really work correctly for the `StudyInfo` case. Really, that should not ever go to cache and should instead act more like sign in, maybe be included in the AuthManager since the goal is to use it to sign in the participant and then it isn't ever used within the app. Let's discuss when you have a chance. Thanks!

2021-07-19 21:08 UTC, nategbrown9 commented
> Upon further consideration, the flow doesn't really work correctly for the `StudyInfo` case. Really, that should not ever go to cache and should instead act more like sign in, maybe be included in the AuthManager since the goal is to use it to sign in the participant and then it isn't ever used within the app. Let's discuss when you have a chance. Thanks!

So something like this on either AuthenticationRepo or StudyRepo? 


`public suspend fun getStudyInfo(studyId: String): ResourceResult<StudyInfo> {
        try {
            val studyInfo = studyApi.getStudyInfo(bridgeConfig.appId, studyId)
            return ResourceResult.Success(studyInfo, ResourceStatus.SUCCESS)
        } catch (err: Throwable) {
            println(err)
        }
        return ResourceResult.Failed(ResourceStatus.FAILED)
    }`

2021-07-19 23:46 UTC, syoung-smallwisdom commented
Yeah, was just wondering which made more sense to you? Seems kinda like a sign-in thing, yeah?

2021-07-20 23:15 UTC, syoung-smallwisdom approved these changes

2021-07-22 20:53 UTC, merged