File uploads for iOS
Sage-Bionetworks/BridgeClientKMM pull request #62
Opened 2021-09-10 19:30 UTC by Erin-Mounts

2021-09-10 19:34 UTC, syoung-smallwisdom reviewed
Nit: Can you rename the git comments to *not* be "wip"? Thanks!

2021-09-10 19:37 UTC, Erin-Mounts commented
> Nit: Can you rename the git comments to _not_ be "wip"? Thanks!

sure, how do I do that?

2021-09-10 19:47 UTC, Erin-Mounts commented
> > Nit: Can you rename the git comments to _not_ be "wip"? Thanks!
> 
> sure, how do I do that?

never mind, I googled it

2021-09-10 23:14 UTC, syoung-smallwisdom reviewed
Needs to point at release build.

I got tired and didn't review the really long file. I'll keep later after taking a break.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on .idea/jarRepositories.xml
> +      <option name="url" value="https://oss.sonatype.org/content/repositories/snapshots" />
Um... ?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on .idea/runConfigurations.xml
> -        <option value="com.android.tools.idea.compose.preview.runconfiguration.ComposePreviewRunConfigurationProducer" />
?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/BridgeClientAppManager.swift
> +                        encryptedArchives[archive.identifier] = encryptedArchive
FYI: This is the archiving code:

```
    /// Encrypt the archive using the given pem file.
    /// - note: This will also delete the unencrypted zip file as a part of cleanup.
    /// - parameters:
    ///     - pemPath: Path to the .pem file to use with CMS encryption.
    ///     - url: Optional URL for the encrypted file. If null, then the  `archiveURL` will be appended with ".encrypted".
    @discardableResult
    public func encryptArchive(using pemPath: String, to url: URL? = nil) throws -> URL {
        guard let _ = self.archive, let archiveURL = self.archiveURL else {
            throw BridgeArchiverError.archiveClosed
        }
        let encryptedURL = url ?? archiveURL.appendingPathExtension("encrypted")
        let data = try Data(contentsOf: archiveURL)
        let encryptedData = try CMSSupport.cmsEncrypt(data, identityPath: pemPath)
        try encryptedData.write(to: encryptedURL)
        try FileManager.default.removeItem(at: archiveURL)
        self.encryptedURL = encryptedURL
        self.archive = nil
        self.archiveURL = nil
        return encryptedURL
    }
```

So below you could do this:

```
                archives.forEach { archive in
                    guard let url = archive.encryptedURL else {
                        print("WARNING! Cannot upload \(archive.identifier)")
                        return
                    }
                    let id = archive.identifier
```

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +import UIKit
What uses UIKit?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX"
What is the difference between this and `JsonModel.ISO8601TimestampFormatter` which uses "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ" and is used elsewhere for bridge timestamps?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public static let shared = BackgroundNetworkManager()
You have this marked as public but the class itself is internal. Why?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public static let backgroundSessionIdentifier = "org.sagebase.backgroundnetworkmanager.session"
You have this marked as public but the class itself is internal. Why?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    private static func isRunningInAppExtension() -> Bool {
It's a singleton, why static?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +class BackgroundNetworkManager: NSObject, URLSessionBackgroundDelegate {
You're mixing internal, public, and private and using static on a singleton. Kinda confusing to read.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public static var _backgroundSession: URLSession? = nil
a public ivar shouldn't have an `_` underscore.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    func queryString(from parameters: Encodable?) -> String? {
Why are you passing in the parameters as an Encodable? Why not just pass in `[String : String]`?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    // TODO: Allow multiple delegates, one for each unique background session identifier.
sign and date all TODO comments.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    // TODO: When supporting multiple sessions (below), does it make sense to share one delegate queue among all of them?
sign and date all TODO comments.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public static var backgroundSessionCompletionHandlers = [String : () -> Void]()
public?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +                // TODO: Update this when support is added for multiple named background sessions.
sign and date TODO's

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        return BackgroundNetworkManager._backgroundSession!
This code feels pretty brittle. I'm struggling to understand why you aren't using dispatch?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        return queryParams.joined(separator: "&")
So, the json encoder is just taking the parameters and wrapping the value in quotation marks and encoding as UTF8. You then unencoded as UTF8 and percent encode it. That's kinda confusing.

Instead you could use reduce:
```
func queryString(from parameters: [String : String]?) -> String? {
    parameters.reduce("") {
        guard let encodedParam = $1.key.addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed),
              let encodedValueString = "\"\($1.value)\"".addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)
        else {
            return $0
        }
        
        let next = "\(encodedParam)=\(encodedValueString)"
        return $0.isEmpty ? next : "\($0)&\(next)"
    }
}
```

Or use compact map:
```
func queryString(from parameters: [String : String]?) -> String? {
    parameters.compactMap { (param, value) in
        guard let encodedParam = param.addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed),
              let encodedValueString = "\"\(value)\"".addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed)
        else {
            return nil
        }
        return "\(encodedParam)=\(encodedValueString)"
    }.joined(separator: "&")
}
```

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        }
So... using an `inout` is a little weird for Swift. Would be better to do this:

```
extension URLRequest {
    mutating fileprivate func addHeaders(_ headers: [String : String]?) {
        let userAgentHeader = IOSBridgeConfig().userAgent
        self.setValue(userAgentHeader, forHTTPHeaderField: "User-Agent")

        let acceptLanguageHeader = Locale.preferredLanguages.joined(separator: ", ")
        self.setValue(acceptLanguageHeader, forHTTPHeaderField: "Accept-Language")

        self.setValue("no-cache", forHTTPHeaderField: "cache-control")
        
        headers?.forEach {
            self.addValue($0.key, forHTTPHeaderField: $0.value)
        }
    }
}
```

And then in the function that builds the request call
```
request.addHeaders(headers)
```

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +            if let queryString = queryString(from: parameters), !queryString.isEmpty {
```
if isGet, let queryString = queryString(from: parameters), !queryString.isEmpty {
```

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public func downloadFile<T>(from URLString: String, method: String, httpHeaders: [String : String]?, parameters: T?, taskDescription: String) -> URLSessionDownloadTask where T: Encodable {
If your `method` has to be either GET or POST, then it would be less brittle to use an enum.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        if backgroundSession.starts(with: BackgroundNetworkManager.backgroundSessionIdentifier) {
Use a guard and exit early.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +               let resumeData = nsError.userInfo[NSURLSessionDownloadTaskResumeData] as? Data {
Why nested if statement?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +}
If it ain't broke... still, you are reinventing the wheel. See `JsonModel` - it has utilities for encoding/decoding.

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/ParticipantFileUploadAPI.swift
> +    public static let shared = ParticipantFileUploadAPI()
Again, the class is internal. Why the public marked accessors?

2021-09-10 23:14 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/Models/PlatformConfigImpl.swift
> +    public let bridgeEnv: PlatformConfigBridgeEnv
`bridgeEnvironment`

2021-09-10 23:14 UTC, syoung-smallwisdom commented on bridgeClient/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Do we know why this file was added?

2021-09-13 19:18 UTC, syoung-smallwisdom requested changes
Lots of nits that don't look like they are breaking changes but might make things a little more future-proof. 

I'm not approving just yet b/c I am concerned about all the Android Studios changes. I don't understand the build system well enough to know if these break things.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +import UIKit
Again, not sure why this uses UIKit?

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            var data = Data(count: length)
Bit messy to use the same ivar name both here and above. Maybe do this instead?

```
try self.withUnsafeFileSystemRepresentation { fileSystemPath -> Data in
```

and leave off the `let data = ` and `return data`

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +        let list = try self.withUnsafeFileSystemRepresentation { fileSystemPath -> [String] in
again, the nested ivars with the same name is a bit messy.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            }
```suggestion
        }
```

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +                let _ = self.uploadManager.requestUploadURL(uploadApi: self, invariantFilePath: relativePath, fileUrl: fileUrl, uploadMetadata: uploadMetadata)
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            let _ = uploadManager.netManager.downloadFile(from: requestString, method: "POST", httpHeaders: headers, parameters: bridgeUploadObject, taskDescription: relativePath)
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            let _ = uploadManager.netManager.downloadFile(from: notifyUrl, method: "POST", httpHeaders: headers, taskDescription: relativePath)
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            guard let _ = uploadApi.fetchNotifyingBridge(for: invariantFilePath) else {
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            let _ = uploadApi.dequeueForRetry(relativePath: invariantFilePath)
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            let _ = removeMapping(String.self, from: invariantFilePath, defaultsKey: self.bridgeFileUploadsKey)
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +        let _ = self.netManager.uploadFile(fileUrl, httpHeaders: headers, to: uploadUrl, taskDescription: invariantFilePath)
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +        let _ = uploadApi.dequeueForRetry(relativePath: invariantFilePath)
Use `@discardableResult` to mark results as "ignorable" and then you don't need the `let _ =`. Alternatively, please add a comment to explain *why* you are ignoring the result.

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +        else {
```
guard error == nil 
else {
    // If the URLSession was deliberately invalidated (i.e., error is nil) then we assume
    // the intention is to cancel and forget all incomplete uploads, including retries.
    // This might be used e.g. to clear out all pending uploads if we receive a 412
    // (Not Consented) error from Bridge or if the participant withdraws from the study.
    self.reset()
    return
}
```

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            let baseDirUrl = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: appGroupIdentifier)
```
if let appGroupIdentifier = IOSBridgeConfig().appGroupIdentifier, appGroupIdentifier.count > 0,
             let baseDirUrl = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: appGroupIdentifier) {
```

2021-09-13 19:18 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/ParticipantFileUploadAPI.swift
> +import UIKit
Again, why UIKit?

Ideally, it would be nice to be able to run this against macOS for GitHub Action swift testing. Swift PM doesn't currently allow setting which os versions a library is built for.

2021-09-13 20:26 UTC, Erin-Mounts commented on .idea/jarRepositories.xml
> +      <option name="url" value="https://oss.sonatype.org/content/repositories/snapshots" />
No idea. I just clicked the Sync Project with Gradle Files button in Android Studio, and ran your build script. I didn't touch this file myself.

2021-09-13 20:27 UTC, Erin-Mounts commented on .idea/runConfigurations.xml
> -        <option value="com.android.tools.idea.compose.preview.runconfiguration.ComposePreviewRunConfigurationProducer" />
¯\\_(ツ)\_/¯

2021-09-13 20:40 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/BridgeClientAppManager.swift
> +                        encryptedArchives[archive.identifier] = encryptedArchive
👍

2021-09-13 20:52 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +import UIKit
Apparently nothing? I think this was part of the boilerplate when I created the blank file and I forgot to remove it.

2021-09-13 21:01 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX"
Apparently nothing. I just didn't know where to look for that when I was making this. Thanks!

2021-09-13 21:03 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public static let shared = BackgroundNetworkManager()
Habit. Or possible copied from a public class without thinking.

2021-09-13 21:07 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public static let backgroundSessionIdentifier = "org.sagebase.backgroundnetworkmanager.session"
Because in previous implementations, the AppDelegate might need to know this to properly handle background url session events. But since the code that handles this now lives in this same module, and the AppDelegate just calls that, it doesn't need to be.

2021-09-13 21:11 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    private static func isRunningInAppExtension() -> Bool {
No good reason. I think the BridgeSDK implementation also was, which made it available even if you were to register a custom network manager. But that doesn't apply here.

2021-09-13 21:16 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +class BackgroundNetworkManager: NSObject, URLSessionBackgroundDelegate {
yeah, that's how it evolved as I developed it. sorry about that.

2021-09-13 21:28 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    func queryString(from parameters: Encodable?) -> String? {
Because the (only) function that calls this one works for all types of requests, not just GETs, and for POSTs the parameters can be passed in as e.g. an UploadRequest object or a ParticipantFile object. That func just passes the parameters arg straight through to this one. I suppose I could have done the check in the caller, but this is ported directly from the original Objective-C implementation and I honestly don't remember my reasoning (if any) for doing it here instead.

2021-09-13 21:28 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    // TODO: Allow multiple delegates, one for each unique background session identifier.
or get rid of them when they no longer apply ;)

2021-09-13 21:29 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    // TODO: When supporting multiple sessions (below), does it make sense to share one delegate queue among all of them?
deleted

2021-09-13 21:29 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public static var backgroundSessionCompletionHandlers = [String : () -> Void]()
yeah, yeah :P

2021-09-13 21:30 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +                // TODO: Update this when support is added for multiple named background sessions.
deleted

2021-09-13 21:39 UTC, nategbrown9 commented on .idea/jarRepositories.xml
> +      <option name="url" value="https://oss.sonatype.org/content/repositories/snapshots" />
All the remote repositories being added here are no longer used. Not sure if this would break anything, but probably safer to just revert the changes to this file.

2021-09-13 21:41 UTC, nategbrown9 commented on .idea/runConfigurations.xml
> -        <option value="com.android.tools.idea.compose.preview.runconfiguration.ComposePreviewRunConfigurationProducer" />
Don't think this should break anything.

2021-09-13 21:42 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        return BackgroundNetworkManager._backgroundSession!
The code in BridgeSDK used dispatch_once to accomplish this, but that's not available in Swift. Or do you mean why use an OperationQueue instead of a DispatchQueue? I guess mainly because I was already using them since the background URLSession delegate queue is an OperationQueue, and it seemed weirder to me to mix-and-match the two types of concurrency management queues.

2021-09-13 21:58 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        }
👍

2021-09-13 22:01 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +            if let queryString = queryString(from: parameters), !queryString.isEmpty {
👍

2021-09-13 22:11 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +        return BackgroundNetworkManager._backgroundSession!
Ock, just did a "What!?! No... That can't be right" and then googled it. Huh. Sorry.

Anyhow, good to know! I guess maybe we revisit in a month when Xcode 13 is released. ¯\_(ツ)_/¯

2021-09-13 22:25 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +    public func downloadFile<T>(from URLString: String, method: String, httpHeaders: [String : String]?, parameters: T?, taskDescription: String) -> URLSessionDownloadTask where T: Encodable {
Yep. Again, this was ported directly from Objective-C. Fixed.

2021-09-13 22:30 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +               let resumeData = nsError.userInfo[NSURLSessionDownloadTaskResumeData] as? Data {
Because if there's an error that *isn't* coupled with resume data from a download task, then I want to fall through and (1) handle any HTTP errors and (2) pass the error along to the backgroundTransferDelegate (i.e. the BridgeFileUploadManager).

2021-09-13 22:48 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +}
👍

2021-09-13 22:50 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/ParticipantFileUploadAPI.swift
> +    public static let shared = ParticipantFileUploadAPI()
Because this class is meant to be public so an app can actually use it. Fixing that.

2021-09-13 22:52 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/Models/PlatformConfigImpl.swift
> +    public let bridgeEnv: PlatformConfigBridgeEnv
👍 (was just echoing what was previously in BridgeSDK/BridgeInfo.plist)

2021-09-13 22:53 UTC, Erin-Mounts commented on bridgeClient/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I sure don't, so if you don't either, then no, "we" don't.

2021-09-13 22:55 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +import UIKit
so that it can register an observer for the UIApplication.didBecomeActiveNotification to retry stuck uploads.

2021-09-13 23:51 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            var data = Data(count: length)
👍

2021-09-13 23:51 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +        let list = try self.withUnsafeFileSystemRepresentation { fileSystemPath -> [String] in
👍

2021-09-13 23:52 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            }
👍

2021-09-14 00:17 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +        else {
👍 (except != instead of == so the else clause happens if it does equal nil)

2021-09-14 00:20 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            let baseDirUrl = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: appGroupIdentifier)
I should have caught that when porting from Obj-C--thanks!

2021-09-14 00:23 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/ParticipantFileUploadAPI.swift
> +import UIKit
Boilerplate. Deleted. 👍

2021-09-14 04:08 UTC, syoung-smallwisdom approved these changes
Looks good. Couple of follow up questions.

2021-09-14 04:08 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/ParticipantFileUploadAPI.swift
> +public struct ParticipantFile: Codable {
FYI: 

1. This is public with all the properties as internal so outside this framework they cannot be seen. 
2. The initializer is internal so it can only be initialized internally.
3. Any reason why the properties are all read/write?

2021-09-14 04:08 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/StudyDataUploadAPI.swift
> +class StudyDataUploadAPI: BridgeFileUploadAPITyped {
Should this also be public?

2021-09-14 04:08 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +protocol BridgeFileUploadAPITyped : BridgeFileUploadAPI {
Should this protocol be public?

2021-09-14 04:08 UTC, syoung-smallwisdom commented on bridgeClient/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Hmmm.... @nategbrown9 ?

2021-09-14 04:08 UTC, syoung-smallwisdom commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +               let resumeData = nsError.userInfo[NSURLSessionDownloadTaskResumeData] as? Data {
Yes... I am not seeing why this wouldn't do the same:

```
        if let nsError = error as NSError?,
           let downloadTask = task as? URLSessionDownloadTask,
           let resumeData = nsError.userInfo[NSURLSessionDownloadTaskResumeData] as? Data {
            // if there's resume data from a download task, use it to retry
            self.retryFailedDownload(downloadTask, for: session, resumeData: resumeData)
            return
        }
```

2021-09-14 15:50 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BackgroundNetworkManager.swift
> +               let resumeData = nsError.userInfo[NSURLSessionDownloadTaskResumeData] as? Data {
Ah. Once again, I'm translating Obj-C too literally and not into idiomatic Swift. Fixed.

2021-09-14 15:52 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +            let _ = uploadApi.dequeueForRetry(relativePath: invariantFilePath)
👍

2021-09-14 15:52 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +        let _ = self.netManager.uploadFile(fileUrl, httpHeaders: headers, to: uploadUrl, taskDescription: invariantFilePath)
👍

2021-09-14 16:04 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/ParticipantFileUploadAPI.swift
> +public struct ParticipantFile: Codable {
1. Good point, removing `public`. If this ever gets refactored to not require it to be Codable (or the Kotlin model objects can be Codable) then this should just use the Kotlin model object.
2. See 1.
3. Only the first three are required, but if I make them all `let` then I can't initialize one without specifying all properties. Fixed those three. I'd like to have made `type` also be `let`, but then it gives a warning that the field can't get overwritten during deserialization, which is fine but I wanted to remove the warning.

2021-09-14 16:06 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/StudyDataUploadAPI.swift
> +class StudyDataUploadAPI: BridgeFileUploadAPITyped {
oops yeah 😅

2021-09-14 16:06 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +protocol BridgeFileUploadAPITyped : BridgeFileUploadAPI {
yeah, again oops

2021-09-14 16:17 UTC, Erin-Mounts commented on SwiftPackage/Sources/BridgeClientUI/File Uploading/BridgeFileUploadManager.swift
> +protocol BridgeFileUploadAPITyped : BridgeFileUploadAPI {
hmm, on second thought--if I make this public, then I get cascading requirements to make a whole bunch of stuff public that I don't think really needs (or ought) to be. If we ever need to support a new Bridge upload API, that support should go in BridgeClient anyway so I will leave this as internal.

2021-09-14 22:06 UTC, nategbrown9 commented on bridgeClient/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
It could contain personalized settings for Android Studio, so we should remove it and add it to git ignore. https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

2021-09-14 23:34 UTC, Erin-Mounts commented on bridgeClient/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@nategbrown9 does this look good for adding to the end of the .gitignore (taken from that link) before I do the dance to remove newly-ignored files from the repo?

```
# Intellij IDE
#
# See https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

.idea/workspace.xml
.idea/usage.statistics.xml
.idea/shelf/
```

2021-09-15 00:04 UTC, Erin-Mounts commented on bridgeClient/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Took me a minute to figure out what's going on here--there's no .gitignore in bridgeClient and apparently the pattern matching in .gitignore files isn't recursive, at least when the pattern includes a partial path? ¯\\_(ツ)\_/¯ anyway, adding a .gitignore to that folder now...

2021-09-15 00:10 UTC, Erin-Mounts commented on bridgeClient/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@nategbrown9 you might want to look over the relevant commit (17d229fae0a77b75904309846359e1c35cb51a09) since it ended up removing some of your user-specific Xcode files for iosApp...

2021-09-15 01:37 UTC, merged